[package]
name = "win-win"
version = "0.0.1"
authors = ["mikael edlund <d34dmeat@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = "0.3.8"
